[package]
name = "arsonist"
version = "0.1.0"
authors = ["Matheus Xavier <mxavier@mail.cmdforge.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.4"
nix = "0.19.0"
libc = "0.2.80"
